// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0UcLkWeAQO8g3rV4LY-nt8YhoHOpXtg',
    appId: '1:1010849088623:web:d1ed5ec5f918aba18b399a',
    messagingSenderId: '1010849088623',
    projectId: 'furniture-b219e',
    authDomain: 'furniture-b219e.firebaseapp.com',
    storageBucket: 'furniture-b219e.appspot.com',
    measurementId: 'G-GFN7FHCX2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyASnMuyIPrgWCdcuEVhDtcnzdrVyQxKM',
    appId: '1:1010849088623:android:e4f58385a94b58e08b399a',
    messagingSenderId: '1010849088623',
    projectId: 'furniture-b219e',
    storageBucket: 'furniture-b219e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw40HYcVbxxaQnmijfRUfRNjcaEOBZBBc',
    appId: '1:1010849088623:ios:eed45f793b7369b38b399a',
    messagingSenderId: '1010849088623',
    projectId: 'furniture-b219e',
    storageBucket: 'furniture-b219e.appspot.com',
    iosBundleId: 'com.example.furniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw40HYcVbxxaQnmijfRUfRNjcaEOBZBBc',
    appId: '1:1010849088623:ios:eed45f793b7369b38b399a',
    messagingSenderId: '1010849088623',
    projectId: 'furniture-b219e',
    storageBucket: 'furniture-b219e.appspot.com',
    iosBundleId: 'com.example.furniture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ0UcLkWeAQO8g3rV4LY-nt8YhoHOpXtg',
    appId: '1:1010849088623:web:0cf21f304888c8048b399a',
    messagingSenderId: '1010849088623',
    projectId: 'furniture-b219e',
    authDomain: 'furniture-b219e.firebaseapp.com',
    storageBucket: 'furniture-b219e.appspot.com',
    measurementId: 'G-QR3X5L2LYY',
  );
}
